FROM python:3.9.6

WORKDIR /app

RUN apt-get update -y \
  && apt install libgl1-mesa-glx -y

COPY requirements.txt /app/requirements.txt

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . /app

CMD gunicorn --workers 8 --bind 0.0.0.0:5000 wsgi:app --timeout 5 --keep-alive 5 --log-level info
